"""create refresh_tokens and fix tokens 2

Revision ID: d98cad74c80f
Revises: 7fbf0a02b526
Create Date: 2025-09-29 20:04:36.609168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd98cad74c80f'
down_revision: Union[str, Sequence[str], None] = '7fbf0a02b526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
